// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testpb.proto

package testpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ninjia struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hp                   uint32   `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ninjia) Reset()         { *m = Ninjia{} }
func (m *Ninjia) String() string { return proto.CompactTextString(m) }
func (*Ninjia) ProtoMessage()    {}
func (*Ninjia) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b98c0ed33edeb52, []int{0}
}

func (m *Ninjia) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ninjia.Unmarshal(m, b)
}
func (m *Ninjia) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ninjia.Marshal(b, m, deterministic)
}
func (m *Ninjia) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ninjia.Merge(m, src)
}
func (m *Ninjia) XXX_Size() int {
	return xxx_messageInfo_Ninjia.Size(m)
}
func (m *Ninjia) XXX_DiscardUnknown() {
	xxx_messageInfo_Ninjia.DiscardUnknown(m)
}

var xxx_messageInfo_Ninjia proto.InternalMessageInfo

func (m *Ninjia) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Ninjia) GetHp() uint32 {
	if m != nil {
		return m.Hp
	}
	return 0
}

type NinJiaHistory struct {
	NinjiaList           []*Ninjia `protobuf:"bytes,1,rep,name=ninjia_list,json=ninjiaList,proto3" json:"ninjia_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NinJiaHistory) Reset()         { *m = NinJiaHistory{} }
func (m *NinJiaHistory) String() string { return proto.CompactTextString(m) }
func (*NinJiaHistory) ProtoMessage()    {}
func (*NinJiaHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b98c0ed33edeb52, []int{1}
}

func (m *NinJiaHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NinJiaHistory.Unmarshal(m, b)
}
func (m *NinJiaHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NinJiaHistory.Marshal(b, m, deterministic)
}
func (m *NinJiaHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NinJiaHistory.Merge(m, src)
}
func (m *NinJiaHistory) XXX_Size() int {
	return xxx_messageInfo_NinJiaHistory.Size(m)
}
func (m *NinJiaHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_NinJiaHistory.DiscardUnknown(m)
}

var xxx_messageInfo_NinJiaHistory proto.InternalMessageInfo

func (m *NinJiaHistory) GetNinjiaList() []*Ninjia {
	if m != nil {
		return m.NinjiaList
	}
	return nil
}

func init() {
	proto.RegisterType((*Ninjia)(nil), "testpb.Ninjia")
	proto.RegisterType((*NinJiaHistory)(nil), "testpb.NinJiaHistory")
}

func init() { proto.RegisterFile("testpb.proto", fileDescriptor_1b98c0ed33edeb52) }

var fileDescriptor_1b98c0ed33edeb52 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x49, 0x2d, 0x2e,
	0x29, 0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x34, 0xb8, 0xd8,
	0xfc, 0x32, 0xf3, 0xb2, 0x32, 0x13, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x78, 0x83, 0x98, 0x32, 0x53, 0x40, 0xfc, 0x8c, 0x02, 0x09, 0x26, 0x08, 0x3f, 0xa3, 0x40,
	0xc9, 0x81, 0x8b, 0xd7, 0x2f, 0x33, 0xcf, 0x2b, 0x33, 0xd1, 0x23, 0xb3, 0xb8, 0x24, 0xbf, 0xa8,
	0x52, 0x48, 0x9f, 0x8b, 0x3b, 0x0f, 0xac, 0x35, 0x3e, 0x27, 0xb3, 0xb8, 0x44, 0x82, 0x51, 0x81,
	0x59, 0x83, 0xdb, 0x88, 0x4f, 0x0f, 0x6a, 0x0d, 0xc4, 0xd4, 0x20, 0x2e, 0x88, 0x12, 0x9f, 0xcc,
	0xe2, 0x92, 0x24, 0x36, 0xb0, 0xd5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x15, 0x1f, 0x16,
	0x99, 0x8a, 0x00, 0x00, 0x00,
}
