// Code generated by protoc-gen-go.
// source: testpb2.proto
// DO NOT EDIT!

/*
Package testpb is a generated protocol buffer package.

It is generated from these files:
	testpb2.proto

It has these top-level messages:
	TestReq
	TestRsp
*/
package testpb

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type TestReq struct {
	Str              *string `protobuf:"bytes,1,opt,name=str" json:"str,omitempty"`
	IntList          []int32 `protobuf:"varint,2,rep,name=int_list" json:"int_list,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TestReq) Reset()         { *m = TestReq{} }
func (m *TestReq) String() string { return proto.CompactTextString(m) }
func (*TestReq) ProtoMessage()    {}

func (m *TestReq) GetStr() string {
	if m != nil && m.Str != nil {
		return *m.Str
	}
	return ""
}

func (m *TestReq) GetIntList() []int32 {
	if m != nil {
		return m.IntList
	}
	return nil
}

type TestRsp struct {
	Sum              *int32 `protobuf:"varint,2,opt,name=sum" json:"sum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TestRsp) Reset()         { *m = TestRsp{} }
func (m *TestRsp) String() string { return proto.CompactTextString(m) }
func (*TestRsp) ProtoMessage()    {}

func (m *TestRsp) GetSum() int32 {
	if m != nil && m.Sum != nil {
		return *m.Sum
	}
	return 0
}

func init() {
}
