FROM ubuntu:16.04

RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
RUN apt-get update && apt-get -y install g++  && apt-get -y install make

RUN mkdir -p /home/services/cpp
COPY counter.cpp Makefile  /home/services/cpp/
WORKDIR /home/services/cpp

RUN make

CMD ["./counter"]

