FROM ubuntu:16.04
RUN sed -i 's#http://archive.ubuntu.com#http://mirrors.163.com#g' /etc/apt/sources.list  && \
        apt-get update && apt-get -y install python

COPY echo.py /home/services/python/
WORKDIR /home/services/python
RUN chmod +x echo.py
CMD ["./echo.py"]


